// qhlist200000.c

inherit SKILL;
#include <ansi.h>;
mapping *quest = ({
        ([      "quest":                "林震南",
                "quest_type":           "杀",
                "time":                 240,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "史青山",
                "quest_type":           "杀",
                "time":                 240,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "独臂神尼",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "庄夫人",
                "quest_type":           "杀",
                "time":                 240,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "高彦超",
                "quest_type":           "杀",
                "time":                 240,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "关安基",
                "quest_type":           "杀",
                "time":                 240,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "贾老六",
                "quest_type":           "杀",
                "time":                 240,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "李力世",
                "quest_type":           "杀",
                "time":                 240,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "茅十八",
                "quest_type":           "杀",
                "time":                 240,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "双儿",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "吴六奇",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "徐天川",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "庄允城",
                "quest_type":           "杀",
                "time":                 240,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "段誉",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "黄眉大师",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "霍先生",
                "quest_type":           "杀",
                "time":                 240,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "木婉清",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "破嗔",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "破疑",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "钟四嫂",
                "quest_type":           "杀",
                "time":                 240,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "崔镖头",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "史镖头",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "王夫人",
                "quest_type":           "杀",
                "time":                 240,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "郑镖头",
                "quest_type":           "杀",
                "time":                 240,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "胡斐",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "萧远山",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "范一飞",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "风良",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "高三娘子",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "韩宝驹",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "韩小莹",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "柯镇恶",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "吕正平",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "南希仁",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "全金发",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "小菊",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "小兰",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "陆冠英",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "张阿生",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "朱聪",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "林朝英",
                "quest_type":           "杀",
                "time":                 600,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "小龙女",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "孙婆婆",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "李沅芷",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "向问天",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "仪和",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "定静师太",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "仪琳",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "秦绢",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "仪清",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "仪文",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "定闲师太",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "定逸师太",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "郑萼",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "仪质",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "刘正风",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "刘夫人",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "刘菁",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "刘芹",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "米为义",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "莫大",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "曲洋",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "向大年",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "曲非烟",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "仪琳",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "袁紫衣",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "老秀才",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "祖千秋",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "陆大有",
                "quest_type":           "杀",
                "time":                 240,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "高根明",
                "quest_type":           "杀",
                "time":                 240,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "小师妹",
                "quest_type":           "杀",
                "time":                 240,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "梁发",
                "quest_type":           "杀",
                "time":                 240,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "令狐冲",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "陆大有",
                "quest_type":           "杀",
                "time":                 240,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "任盈盈",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "施戴子",
                "quest_type":           "杀",
                "time":                 240,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "岳灵珊",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "程青霜",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "符敏仪",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "菊剑",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "兰剑",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "石嫂",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "余婆婆",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "丹青生",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "丁坚",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "黑白子",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "黄钟公",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "施令威",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "秃笔翁",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "陈志益",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "程瑶迦",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "崔志方",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "房志起",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "郝大通",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "姬清虚",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "李志常",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "刘处玄",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "马钰",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "皮清玄",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "祁志诚",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "丘处机",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "申志凡",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "孙不二",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "谭处端",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "王重阳",
                "quest_type":           "杀",
                "time":                 600,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "王处一",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "王志坦",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "尹志平",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "张志光",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "掌经道长",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "掌理道长",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "掌药道长",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "掌园道长",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "赵志敬",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "知客道长",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "刘国轩",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "乔三槐",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "方怡",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "沐剑屏",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "云素梅",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "迟百城",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "建除道人",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "江百胜",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "天柏道人",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "天门道人",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "天松道人",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "天乙道人",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "程英",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "周伯通",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "本参",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "本尘",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "本观",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "本相",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "本因",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "枯荣大师",
                "quest_type":           "杀",
                "time":                 600,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "甘宝宝",
                "quest_type":           "杀",
                "time":                 600,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "黄眉大师",
                "quest_type":           "杀",
                "time":                 600,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "木婉清",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "钟灵",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "白自在",
                "quest_type":           "杀",
                "time":                 600,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "史婆婆",
                "quest_type":           "杀",
                "time":                 600,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "石破天",
                "quest_type":           "杀",
                "time":                 600,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "冯阿三",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "苟读",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "康广陵",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "苏星河",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "逍遥子",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "薛慕华",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "阿凡提",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "刘承风",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "陆天抒",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "水岱",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "央宗",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "卓玛",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "阿碧",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "阿朱",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "巴天石",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "刀白凤",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "段正淳",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "范骅",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "傅思归",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "高升泰",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "古笃诚",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "华赫艮",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "朱丹臣",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "褚万里",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "贝锦仪",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "静道师太",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "道明小师父",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "丁敏君",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "方碧琳",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "静风师太",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "静和师太",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "静慧师太",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "纪晓芙",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "静迦师太",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "静空师太",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "李明霞",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "赵灵珠",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "灭绝师太",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "苏梦清",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "静闲师太",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "静心师太",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "静虚师太",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "静玄师太",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "静照师太",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "静真师太",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "周芷若",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "何不净",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "洪七公",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "简长老",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "江上游",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "空空儿",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "李斧头",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "黎生",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "梁长老",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "鲁有脚",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "马俱为",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "余洪兴",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "左全",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "矮老者",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "成不忧",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "丛不弃",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "封不平",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "风清扬",
                "quest_type":           "杀",
                "time":                 700,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "高老者",
                "quest_type":           "杀",
                "time":                 700,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "令狐冲",
                "quest_type":           "杀",
                "time":                 700,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "岳不群",
                "quest_type":           "杀",
                "time":                 700,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "岳夫人",
                "quest_type":           "杀",
                "time":                 700,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "梅剑",
                "quest_type":           "杀",
                "time":                 700,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "天山童姥",
                "quest_type":           "杀",
                "time":                 700,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "虚竹",
                "quest_type":           "杀",
                "time":                 700,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "范遥",
                "quest_type":           "杀",
                "time":                 700,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "韦一笑",
                "quest_type":           "杀",
                "time":                 700,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "小昭",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "谢逊",
                "quest_type":           "杀",
                "time":                 600,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "杨逍",
                "quest_type":           "杀",
                "time":                 600,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "殷天正",
                "quest_type":           "杀",
                "time":                 600,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "张无忌",
                "quest_type":           "杀",
                "time":                 600,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "澄观",
                "quest_type":           "杀",
                "time":                 600,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "澄和",
                "quest_type":           "杀",
                "time":                 600,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "澄寂",
                "quest_type":           "杀",
                "time":                 600,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "澄坚",
                "quest_type":           "杀",
                "time":                 600,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "澄净",
                "quest_type":           "杀",
                "time":                 600,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "澄灵",
                "quest_type":           "杀",
                "time":                 600,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "澄灭",
                "quest_type":           "杀",
                "time":                 600,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "澄明",
                "quest_type":           "杀",
                "time":                 600,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "澄尚",
                "quest_type":           "杀",
                "time":                 600,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "澄识",
                "quest_type":           "杀",
                "time":                 600,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "澄思",
                "quest_type":           "杀",
                "time":                 600,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "澄心",
                "quest_type":           "杀",
                "time":                 600,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "澄信",
                "quest_type":           "杀",
                "time":                 600,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "澄行",
                "quest_type":           "杀",
                "time":                 600,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "澄意",
                "quest_type":           "杀",
                "time":                 600,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "澄欲",
                "quest_type":           "杀",
                "time":                 600,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "澄知",
                "quest_type":           "杀",
                "time":                 600,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "澄志",
                "quest_type":           "杀",
                "time":                 600,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "达摩老祖",
                "quest_type":           "杀",
                "time":                 800,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "道尘禅师",
                "quest_type":           "杀",
                "time":                 600,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "道成禅师",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "道果禅师",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "道觉禅师",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "道品禅师",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "道相禅师",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "道象禅师",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "道一禅师",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "道正禅师",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "渡厄",
                "quest_type":           "杀",
                "time":                 600,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "渡劫",
                "quest_type":           "杀",
                "time":                 600,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "渡难",
                "quest_type":           "杀",
                "time":                 600,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "慧合尊者",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "慧洁尊者",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "慧空尊者",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "慧名尊者",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "慧如尊者",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "慧色尊者",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "慧修尊者",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "慧虚尊者",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "慧真尊者",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "清法比丘",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "清观比丘",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "清乐比丘",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "清善比丘",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "清为比丘",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "清闻比丘",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "清无比丘",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "清晓比丘",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "清缘比丘",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "玄悲大师",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "玄慈大师",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "玄苦大师",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "玄难大师",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "玄痛大师",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "冯默风" ,
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "黄药师",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "陆乘风" ,
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "曲灵风" ,
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "黄蓉",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "谷虚道长",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "莫声谷",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "清虚道长",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "张翠山",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "守园道长",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "宋远桥",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "张松溪",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "宋青书",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "俞岱岩",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "殷梨亭",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "俞莲舟",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "张三丰",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "灵虚道长",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "制香道长",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "龙岛主",
                "quest_type":           "杀",
                "time":                 700,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "木岛主",
                "quest_type":           "杀",
                "time":                 700,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "陈近南",
                "quest_type":           "杀",
                "time":                 700,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "马超兴",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "玄贞道长",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            240,
                "pot_bonus":            50,
                "score" :               20
        ]),
});

mapping query_quest()
{
        return quest[random(sizeof(quest))];
}
