// qhlist30000.c

inherit SKILL;
#include <ansi.h>;
mapping *quest = ({
        ([      "quest":                "陪练童子",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "镖头",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "林震南",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "史青山",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "武将",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "崔莺莺",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "程玉环",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "卖花姑娘",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "庄夫人",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "高彦超",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "顾炎武",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "关安基",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "女管家",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "胡掌柜",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "客店伙计",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "屠宰场伙计",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "药铺伙计",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "贾老六",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "李力世",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "茅十八",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "双儿",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "铁匠",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "吴六奇",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "戏子",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "徐天川",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "丫环",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "庄允城",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "女管家",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "酸秀才",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "茶博士",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "士兵",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "台夷商贩",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "南国姑娘",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "宫女",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "管家",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "养花女",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "霍先生",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "江湖艺人",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "砍竹人",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "盛皮罗客商",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "猎人",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "台夷猎人",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "马夫",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "木婉清",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "牧羊女",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "牧羊人",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "农夫",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "台夷农妇",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "农夫",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "摆夷老叟",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "皮货商",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "破嗔",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "破疑",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "少女",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "石匠",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "台夷商贩",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "素衣卫士",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "黄衣卫士",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "锦衣卫士",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "乌夷商贩",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "小道姑",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "薛老板",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "养蚕女",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "游客",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "渔夫",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "张朝唐",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "张康",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "钟四嫂",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "钟小二",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "白二",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "陈七",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "崔镖头",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "戈什哈",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "林震南",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "史镖头",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "王夫人",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "郑镖头",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "范一飞",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "风良",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "高三娘子",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "韩宝驹",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "韩小莹",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "太湖豪杰",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "柯镇恶",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "吕正平",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "南希仁",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "裘千丈",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "全金发",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "书童",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "小菊",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "小兰",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "陆冠英",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "张阿生",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "朱聪",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "孙婆婆",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "红花会众",
                "quest_type":           "杀",
                "time":                 450,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "绿营会众",
                "quest_type":           "杀",
                "time":                 450,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "红娘",
                "quest_type":           "杀",
                "time":                 450,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "李沅芷",
                "quest_type":           "杀",
                "time":                 450,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "仪和",
                "quest_type":           "杀",
                "time":                 450,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "仪琳",
                "quest_type":           "杀",
                "time":                 450,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "秦绢",
                "quest_type":           "杀",
                "time":                 450,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "仪清",
                "quest_type":           "杀",
                "time":                 450,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "仪文",
                "quest_type":           "杀",
                "time":                 450,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "哑妇",
                "quest_type":           "杀",
                "time":                 450,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "郑萼",
                "quest_type":           "杀",
                "time":                 450,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "仪质",
                "quest_type":           "杀",
                "time":                 450,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "茶博士",
                "quest_type":           "杀",
                "time":                 450,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "刘夫人",
                "quest_type":           "杀",
                "time":                 450,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "刘菁",
                "quest_type":           "杀",
                "time":                 450,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "刘芹",
                "quest_type":           "杀",
                "time":                 450,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "米为义",
                "quest_type":           "杀",
                "time":                 450,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "向大年",
                "quest_type":           "杀",
                "time":                 450,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "曲非烟",
                "quest_type":           "杀",
                "time":                 450,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "仪琳",
                "quest_type":           "杀",
                "time":                 450,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "老秀才",
                "quest_type":           "杀",
                "time":                 200,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "祖千秋",
                "quest_type":           "杀",
                "time":                 450,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "陆大有",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "高根明",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "小师妹",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "梁发",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "小猴",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "陆大有",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "施戴子",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "岳灵珊",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "程青霜",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "符敏仪",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "菊剑",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "兰剑",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "李嫂",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "蒙面女郎",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "石嫂",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "余婆婆",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "丁坚",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "施令威",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "陈志益",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "程瑶迦",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "崔志方",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "房志起",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "姬清虚",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "李志常",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "皮清玄",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "祁志诚",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "申志凡",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "王志坦",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "尹志平",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "侯员外",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "张志光",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "掌经道长",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "掌理道长",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "掌药道长",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "掌园道长",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "赵志敬",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "知客道长",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "刘国轩",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "乔三槐",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "扫地僧",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "护林僧兵",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "执法僧兵",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "守寺僧兵",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "方怡",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "沐剑屏",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "云素梅",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "苏州女孩",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "苏州少女",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "迟百城",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "建除道人",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "江百胜",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "游方和尚",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "天柏道人",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "天松道人",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "天乙道人",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "程英",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "护塔僧",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "老年僧人",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "扫地僧",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "翠花",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "甘宝宝",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "木婉清",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "钟灵",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "小翠",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "石破天",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "冯阿三",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "苟读",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "康广陵",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "薛慕华",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "阿拉木罕",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "阿凡提",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "买卖提",
                "quest_type":           "杀",
                "time":                 200,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "波斯商人",
                "quest_type":           "杀",
                "time":                 200,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "刘承风",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "陆天抒",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "水岱",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "央宗",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "卓玛",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "阿碧",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "阿朱",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "素素",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "巴天石",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "刀白凤",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "范骅",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "傅思归",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "高升泰",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "古笃诚",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "华赫艮",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "朱丹臣",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "褚万里",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "贝锦仪",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "静道师太",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "道明小师父",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "方碧琳",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "静风师太",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "静和师太",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "静慧师太",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "纪晓芙",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "静迦师太",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "静空师太",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "李明霞",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "赵灵珠",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "苏梦清",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "文方小师太",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "文晖小师太",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "文清小师太",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "文音小师太",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "静闲师太",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "静心师太",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "静虚师太",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "静玄师太",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "静照师太",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "静真师太",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "何不净",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "江上游",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "空空儿",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "快活三",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "李斧头",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "黎生",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "马俱为",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "莫不收",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "裘万家",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "余洪兴",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "赵狗儿",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "左全",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "梅剑",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "虚竹",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "小昭",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "澄观",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "澄和",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "澄寂",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "澄坚",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "澄净",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "澄灵",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "澄灭",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "澄明",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "澄尚",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "澄识",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "澄思",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "澄心",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "澄信",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "澄行",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "澄意",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "澄欲",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "澄知",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "澄志",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "道尘禅师",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "道成禅师",
                "quest_type":           "杀",
                "time":                 200,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "道果禅师",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "道觉禅师",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "道品禅师",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "道相禅师",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "道象禅师",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "道一禅师",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "道正禅师",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "慧合尊者",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "慧洁尊者",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "慧空尊者",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "慧名尊者",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "慧如尊者",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "慧色尊者",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "慧修尊者",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "慧虚尊者",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "慧真尊者",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "清法比丘",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "清观比丘",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "清乐比丘",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "清善比丘",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "清为比丘",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "清闻比丘",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "清无比丘",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "清晓比丘",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "清缘比丘",
                "quest_type":           "杀",
                "time":                 350,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "托钵僧",
                "quest_type":           "杀",
                "time":                 200,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "行者",
                "quest_type":           "杀",
                "time":                 200,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "虚明",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "虚通",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "冯默风" ,
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "陆乘风" ,
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "曲灵风" ,
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "黄蓉",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "八卦弟子",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "道童",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "伐木道士",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "谷虚道长",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "明月",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "清风",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "清虚道长",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "守园道长",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "五行弟子",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "宋青书",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "灵虚道长",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "制香道长",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "马超兴",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
        ([      "quest":                "玄贞道长",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            44,
                "score" :               20
        ]),
});

mapping query_quest()
{
        return quest[random(sizeof(quest))];
}
