// qlist22000.c
inherit SKILL;

mapping *quest = ({
        ([      "quest":                "扫地僧",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            60,
                "pot_bonus":            10,
                "score" :               5
        ]),
        ([      "quest":                "维吾尔族长袍",
                "quest_type":           "寻",
                "time":                 800,
                "exp_bonus":            40,
                "pot_bonus":            10,
                "score" :               5
        ]),
        ([      "quest":                "流氓头",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            30,
                "pot_bonus":            10,
                "score" :               10
        ]),
        ([      "quest":                "牛皮酒袋",
                "quest_type":           "寻",
                "time":                 800,
                "exp_bonus":            10,
                "pot_bonus":            3,
                "score" :               5
        ]),
        ([      "quest":                "清闻比丘",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            15,
                "score" :               20
        ]),
        ([      "quest":                "金戒指",
                "quest_type":           "寻",
                "time":                 800,
                "exp_bonus":            30,
                "pot_bonus":            9,
                "score" :               5
        ]),
        ([      "quest":                "林平之",
                "quest_type":           "杀",
                "time":                 200,
                "exp_bonus":            30,
                "pot_bonus":            10,
                "score" :               5
        ]),
        ([      "quest":                "卖花姑娘",
                "quest_type":           "杀",
                "time":                 100,
                "exp_bonus":            20,
                "pot_bonus":            6,
                "score" :               5
        ]),
        ([      "quest":                "狗皮",
                "quest_type":           "寻",
                "time":                 100,
                "exp_bonus":            10,
                "pot_bonus":            5,
                "score" :               5
        ]),
        ([      "quest":                "挑夫",
                "quest_type":           "杀",
                "time":                 200,
                "exp_bonus":            15,
                "pot_bonus":            6,
                "score" :               5
        ]),
        ([      "quest":                "进香客",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            10,
                "pot_bonus":            4,
                "score" :               5
        ]),
        ([      "quest":                "小桂子",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            10,
                "pot_bonus":            7,
                "score" :               5
        ]),
        ([      "quest":                "崔员外",
                "quest_type":           "杀",
                "time":                 600,
                "exp_bonus":            50,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "崔莺莺",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            50,
                "pot_bonus":            15,
                "score" :               20
        ]),
        ([      "quest":                "家丁",
                "quest_type":           "杀",
                "time":                 100,
                "exp_bonus":            30,
                "pot_bonus":            7,
                "score" :               5
        ]),
        ([      "quest":                "戒刀",
                "quest_type":           "寻",
                "time":                 800,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "林平之",
                "quest_type":           "杀",
                "time":                 800,
                "exp_bonus":            40,
                "pot_bonus":            13,
                "score" :               5
        ]),
        ([      "quest":                "护寺武僧",
                "quest_type":           "杀",
                "time":                 100,
                "exp_bonus":            30,
                "pot_bonus":            10,
                "score" :               5
        ]),
        ([      "quest":                "知客僧",
                "quest_type":           "杀",
                "time":                 100,
                "exp_bonus":            30,
                "pot_bonus":            10,
                "score" :               5
        ]),
        ([      "quest":                "哈密瓜",
                "quest_type":           "寻",
                "time":                 800,
                "exp_bonus":            30,
                "pot_bonus":            10,
                "score" :               5
        ]),
        ([      "quest":                "阿拉木罕",
                "quest_type":           "杀",
                "time":                 150,
                "exp_bonus":            30,
                "pot_bonus":            10,
                "score" :               5
        ]),
        ([      "quest":                "太极十三势",
                "quest_type":           "寻",
                "time":                 100,
                "exp_bonus":            20,
                "pot_bonus":            10,
                "score" :               5
        ]),
        ([      "quest":                "道童",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            17,
                "score" :               15
        ]),
        ([      "quest":                "清风",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            17,
                "score" :               15
        ]),
        ([      "quest":                "明月",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            17,
                "score" :               15
        ]),
        ([      "quest":                "灰色道袍",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            30,
                "pot_bonus":            15,
                "score" :               5
        ]),
        ([      "quest":                "波斯商人",
                "quest_type":           "杀",
                "time":                 200,
                "exp_bonus":            30,
                "pot_bonus":            16,
                "score" :               5
        ]),
        ([      "quest":                "买卖提",
                "quest_type":           "杀",
                "time":                 700,
                "exp_bonus":            50,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "白衣少女",
                "quest_type":           "杀",
                "time":                 800,
                "exp_bonus":            20,
                "pot_bonus":            8,
                "score" :               5
        ]),
        ([      "quest":                "阿紫",
                "quest_type":           "杀",
                "time":                 900,
                "exp_bonus":            50,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "门卫",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "狗皮",
                "quest_type":           "寻",
                "time":                 300,
                "exp_bonus":            10,
                "pot_bonus":            9,
                "score" :               5
        ]),
        ([      "quest":                "兔肉",
                "quest_type":           "寻",
                "time":                 300,
                "exp_bonus":            15,
                "pot_bonus":            5,
                "score" :               5
        ]),
        ([      "quest":                "兰剑",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            50,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "青色道袍",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            30,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "星宿派鼓手",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            20,
                "pot_bonus":            8,
                "score" :               5
        ]),
        ([      "quest":                "铜钵",
                "quest_type":           "寻",
                "time":                 300,
                "exp_bonus":            20,
                "pot_bonus":            10,
                "score" :               5
        ]),
        ([      "quest":                "谷虚道长",
                "quest_type":           "杀",
                "time":                 600,
                "exp_bonus":            30,
                "pot_bonus":            10,
                "score" :               5
        ]),
        ([      "quest":                "清心散",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            10,
                "score" :               5
        ]),
});

mapping query_quest()
{
        return quest[random(sizeof(quest))];
}

