// qlist13000.c
inherit SKILL;

mapping *quest = ({
        ([      "quest":                "卖花姑娘",
                "quest_type":           "杀",
                "time":                 200,
                "exp_bonus":            30,
                "pot_bonus":            10,
                "score" :               5
        ]),
        ([      "quest":                "匕首",
                "quest_type":           "寻",
                "time":                 100,
                "exp_bonus":            30,
                "pot_bonus":            10,
                "score" :               5
        ]),
        ([      "quest":                "杨永福",
                "quest_type":           "杀",
                "time":                 60,
                "exp_bonus":            30,
                "pot_bonus":            10,
                "score" :               5
        ]),
        ([      "quest":                "挑夫",
                "quest_type":           "杀",
                "time":                 50,
                "exp_bonus":            30,
                "pot_bonus":            10,
                "score" :               5
        ]),
        ([      "quest":                "船夫",
                "quest_type":           "杀",
                "time":                 150,
                "exp_bonus":            40,
                "pot_bonus":            10,
                "score" :               5
        ]),
        ([      "quest":                "僧棍",
                "quest_type":           "寻",
                "time":                 200,
                "exp_bonus":            20,
                "pot_bonus":            10,
                "score" :               5
        ]),
        ([      "quest":                "护寺武僧",
                "quest_type":           "杀",
                "time":                 150,
                "exp_bonus":            30,
                "pot_bonus":            10,
                "score" :               5
        ]),
        ([      "quest":                "知客僧",
                "quest_type":           "杀",
                "time":                 150,
                "exp_bonus":            30,
                "pot_bonus":            10,
                "score" :               5
        ]),
        ([      "quest":                "羊肉串",
                "quest_type":           "寻",
                "time":                 800,
                "exp_bonus":            20,
                "pot_bonus":            10,
                "score" :               5
        ]),
        ([      "quest":                "托钵僧",
                "quest_type":           "杀",
                "time":                 200,
                "exp_bonus":            30,
                "pot_bonus":            10,
                "score" :               5
        ]),
        ([      "quest":                "黑色袈裟",
                "quest_type":           "寻",
                "time":                 100,
                "exp_bonus":            20,
                "pot_bonus":            10,
                "score" :               5
        ]),
        ([      "quest":                "香火道人",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            50,
                "pot_bonus":            20,
                "score" :               15
        ]),
        ([      "quest":                "钥匙",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            30,
                "pot_bonus":            15,
                "score" :               5
        ]),
        ([      "quest":                "肥肥",
                "quest_type":           "杀",
                "time":                 200,
                "exp_bonus":            30,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "乌鸦",
                "quest_type":           "杀",
                "time":                 700,
                "exp_bonus":            50,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "羊肉串",
                "quest_type":           "寻",
                "time":                 800,
                "exp_bonus":            50,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "清心散",
                "quest_type":           "寻",
                "time":                 900,
                "exp_bonus":            50,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "小松鼠",
                "quest_type":           "杀",
                "time":                 200,
                "exp_bonus":            30,
                "pot_bonus":            10,
                "score" :               5
        ]),
        ([      "quest":                "狗皮",
                "quest_type":           "寻",
                "time":                 300,
                "exp_bonus":            50,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "欧阳克",
                "quest_type":           "杀",
                "time":                 900,
                "exp_bonus":            120,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "知客道长",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            50,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "大刀",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            30,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "小喇嘛",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            30,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "铜号",
                "quest_type":           "寻",
                "time":                 300,
                "exp_bonus":            20,
                "pot_bonus":            10,
                "score" :               5
        ]),
        ([      "quest":                "道童",
                "quest_type":           "杀",
                "time":                 100,
                "exp_bonus":            30,
                "pot_bonus":            10,
                "score" :               5
        ]),
        ([      "quest":                "方怡",
                "quest_type":           "杀",
                "time":                 600,
                "exp_bonus":            30,
                "pot_bonus":            30,
                "score" :               7
        ]),
        ([      "quest":                "铜钹",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "仆人",
                "quest_type":           "杀",
                "time":                 800,
                "exp_bonus":            50,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "镖头",
                "quest_type":           "杀",
                "time":                 100,
                "exp_bonus":            20,
                "pot_bonus":            10,
                "score" :               5
        ]),
        ([      "quest":                "林平之",
                "quest_type":           "杀",
                "time":                 200,
                "exp_bonus":            20,
                "pot_bonus":            10,
                "score" :               5
        ]),
        ([      "quest":                "托钵僧",
                "quest_type":           "杀",
                "time":                 200,
                "exp_bonus":            30,
                "pot_bonus":            10,
                "score" :               5
        ]),
        ([      "quest":                "青布僧衣",
                "quest_type":           "寻",
                "time":                 800,
                "exp_bonus":            20,
                "pot_bonus":            10,
                "score" :               5
        ]),
        ([      "quest":                "游方和尚",
                "quest_type":           "杀",
                "time":                 100,
                "exp_bonus":            20,
                "pot_bonus":            10,
                "score" :               5
        ]),
        ([      "quest":                "刀客",
                "quest_type":           "杀",
                "time":                 600,
                "exp_bonus":            50,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "趟子手",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "衙役",
                "quest_type":           "杀",
                "time":                 200,
                "exp_bonus":            30,
                "pot_bonus":            15,
                "score" :               5
        ]),
        ([      "quest":                "沐剑屏",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "流氓头",
                "quest_type":           "杀",
                "time":                 200,
                "exp_bonus":            30,
                "pot_bonus":            10,
                "score" :               5
        ]),
        ([      "quest":                "傣族首领",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            60,
                "pot_bonus":            25,
                "score" :               5
        ]),
        ([      "quest":                "韦春芳",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            60,
                "pot_bonus":            25,
                "score" :               5
        ]),
});

mapping query_quest()
{
        return quest[random(sizeof(quest))];
}

