// qlist100000.c
inherit SKILL;

mapping *quest = ({
        ([      "quest":                "李教头",
                "quest_type":           "杀",
                "time":                 280,
                "exp_bonus":            100,
                "pot_bonus":            15,
                "score" :               150   //over
        ]),
        ([      "quest":                "欧阳克",
                "quest_type":           "杀",
                "time":                 780,
                "exp_bonus":            170,
                "pot_bonus":            35,
                "score" :               150   //over
        ]),
        ([      "quest":                "拂尘",
                "quest_type":           "寻",
                "time":                 600,
                "exp_bonus":            80,
                "pot_bonus":            15,
                "score" :               50   //over
        ]),
        ([      "quest":                "细铁杆",
                "quest_type":           "寻",
                "time":                 800,
                "exp_bonus":            100,
                "pot_bonus":            35,
                "score" :               50   //over
        ]),
        ([      "quest":                "崔员外",
                "quest_type":           "杀",
                "time":                 800,
                "exp_bonus":            150,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "海公公",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "齐眉棍",
                "quest_type":           "寻",
                "time":                 800,
                "exp_bonus":            180,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "崔莺莺",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            100,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "游讯",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            150,
                "pot_bonus":            25,
                "score" :               5
        ]),
        ([      "quest":                "空空儿",
                "quest_type":           "杀",
                "time":                 600,
                "exp_bonus":            100,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "戒刀",
                "quest_type":           "寻",
                "time":                 800,
                "exp_bonus":            100,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "扫地僧",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            100,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "劳德诺",
                "quest_type":           "杀",
                "time":                 520,
                "exp_bonus":            120,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "梁发",
                "quest_type":           "杀",
                "time":                 520,
                "exp_bonus":            120,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "施戴子",
                "quest_type":           "杀",
                "time":                 520,
                "exp_bonus":            120,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "高根明",
                "quest_type":           "杀",
                "time":                 520,
                "exp_bonus":            120,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "岳灵珊",
                "quest_type":           "杀",
                "time":                 520,
                "exp_bonus":            120,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "李莫愁",
                "quest_type":           "杀",
                "time":                 620,
                "exp_bonus":            220,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "余婆婆",
                "quest_type":           "杀",
                "time":                 620,
                "exp_bonus":            220,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "买卖提",
                "quest_type":           "杀",
                "time":                 620,
                "exp_bonus":            220,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "出尘子",
                "quest_type":           "杀",
                "time":                 620,
                "exp_bonus":            220,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "兰剑",
                "quest_type":           "杀",
                "time":                 620,
                "exp_bonus":            220,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "梅剑",
                "quest_type":           "杀",
                "time":                 620,
                "exp_bonus":            220,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "乌鸦",
                "quest_type":           "杀",
                "time":                 100,
                "exp_bonus":            20,
                "pot_bonus":            5,
                "score" :               5
        ]),
        ([      "quest":                "欧阳克",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            220,
                "pot_bonus":            35,
                "score" :               20
        ]),
        ([      "quest":                "林震南",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            160,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "羊鞭",
                "quest_type":           "寻",
                "time":                 800,
                "exp_bonus":            80,
                "pot_bonus":            25,
                "score" :               5
        ]),
        ([      "quest":                "清闻比丘",
                "quest_type":           "杀",
                "time":                 700,
                "exp_bonus":            120,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "黎生",
                "quest_type":           "杀",
                "time":                 700,
                "exp_bonus":            190,
                "pot_bonus":            29,
                "score" :               5
        ]),
        ([      "quest":                "左全",
                "quest_type":           "杀",
                "time":                 700,
                "exp_bonus":            180,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "衙役服",
                "quest_type":           "寻",
                "time":                 200,
                "exp_bonus":            100,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "谷虚道长",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            18,
                "score" :               5
        ]),
        ([      "quest":                "摘星子",
                "quest_type":           "杀",
                "time":                 700,
                "exp_bonus":            190,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "狮吼子",
                "quest_type":           "杀",
                "time":                 700,
                "exp_bonus":            190,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "出尘子",
                "quest_type":           "杀",
                "time":                 700,
                "exp_bonus":            190,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "采花子",
                "quest_type":           "杀",
                "time":                 700,
                "exp_bonus":            190,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "苏荃",
                "quest_type":           "杀",
                "time":                 700,
                "exp_bonus":            190,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "殷锦",
                "quest_type":           "杀",
                "time":                 700,
                "exp_bonus":            190,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "无根道长",
                "quest_type":           "杀",
                "time":                 700,
                "exp_bonus":            190,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "张淡月",
                "quest_type":           "杀",
                "time":                 700,
                "exp_bonus":            190,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "许雪亭",
                "quest_type":           "杀",
                "time":                 700,
                "exp_bonus":            190,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "陆高轩",
                "quest_type":           "杀",
                "time":                 700,
                "exp_bonus":            190,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "胖头陀",
                "quest_type":           "杀",
                "time":                 700,
                "exp_bonus":            190,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "瘦头陀",
                "quest_type":           "杀",
                "time":                 700,
                "exp_bonus":            190,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "吴六奇",
                "quest_type":           "杀",
                "time":                 700,
                "exp_bonus":            190,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "九翼道人",
                "quest_type":           "杀",
                "time":                 700,
                "exp_bonus":            190,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "史登达",
                "quest_type":           "杀",
                "time":                 700,
                "exp_bonus":            190,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "狄修",
                "quest_type":           "杀",
                "time":                 700,
                "exp_bonus":            190,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "万大平",
                "quest_type":           "杀",
                "time":                 700,
                "exp_bonus":            190,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "迟百城",
                "quest_type":           "杀",
                "time":                 700,
                "exp_bonus":            190,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "仪和",
                "quest_type":           "杀",
                "time":                 700,
                "exp_bonus":            190,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "仪清",
                "quest_type":           "杀",
                "time":                 700,
                "exp_bonus":            190,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "仪质",
                "quest_type":           "杀",
                "time":                 700,
                "exp_bonus":            190,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "仪文",
                "quest_type":           "杀",
                "time":                 700,
                "exp_bonus":            190,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "田伯光",
                "quest_type":           "杀",
                "time":                 700,
                "exp_bonus":            190,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "陆天抒",
                "quest_type":           "杀",
                "time":                 700,
                "exp_bonus":            190,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "花铁干",
                "quest_type":           "杀",
                "time":                 700,
                "exp_bonus":            190,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "刘乘风",
                "quest_type":           "杀",
                "time":                 700,
                "exp_bonus":            190,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "水岱",
                "quest_type":           "杀",
                "time":                 700,
                "exp_bonus":            190,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "胜谛",
                "quest_type":           "杀",
                "time":                 700,
                "exp_bonus":            190,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "宝象",
                "quest_type":           "杀",
                "time":                 700,
                "exp_bonus":            190,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "善勇",
                "quest_type":           "杀",
                "time":                 700,
                "exp_bonus":            190,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "玉萧",
                "quest_type":           "寻",
                "time":                 800,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "明珠",
                "quest_type":           "寻",
                "time":                 800,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "拳谱总诀",
                "quest_type":           "寻",
                "time":                 800,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "掌法总谱",
                "quest_type":           "寻",
                "time":                 800,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "棋谱",
                "quest_type":           "寻",
                "time":                 800,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "玉女剑谱",
                "quest_type":           "寻",
                "time":                 800,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "天山器法",
                "quest_type":           "寻",
                "time":                 800,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "龙泉剑",
                "quest_type":           "寻",
                "time":                 800,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "圣火令",
                "quest_type":           "寻",
                "time":                 800,
                "exp_bonus":            200,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "家丁",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            50,
                "pot_bonus":            10,
                "score" :               15
        ]),
        ([      "quest":                "玄贞道人",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            80,
                "pot_bonus":            27,
                "score" :               5
        ]),
        ([      "quest":                "卖花姑娘",
                "quest_type":           "杀",
                "time":                 100,
                "exp_bonus":            30,
                "pot_bonus":            7,
                "score" :               5
        ]),
        ([      "quest":                "高彦超",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            30,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "建除道人",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            30,
                "pot_bonus":            20,
                "score" :               5
        ]),
});

mapping query_quest()
{
        return quest[random(sizeof(quest))];
}

