// qlist60000.c
inherit SKILL;

mapping *quest = ({
        ([      "quest":                "李教头",
                "quest_type":           "杀",
                "time":                 280,
                "exp_bonus":            100,
                "pot_bonus":            15,
                "score" :               150   //over
        ]),
        ([      "quest":                "劳德诺",
                "quest_type":           "杀",
                "time":                 580,
                "exp_bonus":            150,
                "pot_bonus":            25,
                "score" :               150   //over
        ]),
        ([      "quest":                "傅思归",
                "quest_type":           "杀",
                "time":                 780,
                "exp_bonus":            200,
                "pot_bonus":            45,
                "score" :               150   //over
        ]),
        ([      "quest":                "拂尘",
                "quest_type":           "寻",
                "time":                 600,
                "exp_bonus":            80,
                "pot_bonus":            15,
                "score" :               50   //over
        ]),
        ([      "quest":                "黑色长衫",
                "quest_type":           "寻",
                "time":                 700,
                "exp_bonus":            100,
                "pot_bonus":            25,
                "score" :               50   //over
        ]),
        ([      "quest":                "崔员外",
                "quest_type":           "杀",
                "time":                 800,
                "exp_bonus":            150,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "海公公",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "齐眉棍",
                "quest_type":           "寻",
                "time":                 800,
                "exp_bonus":            180,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "崔莺莺",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            100,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "游讯",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            150,
                "pot_bonus":            25,
                "score" :               5
        ]),
        ([      "quest":                "空空儿",
                "quest_type":           "杀",
                "time":                 600,
                "exp_bonus":            100,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "戒刀",
                "quest_type":           "寻",
                "time":                 800,
                "exp_bonus":            100,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "扫地僧",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            100,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "管家",
                "quest_type":           "杀",
                "time":                 320,
                "exp_bonus":            120,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "李莫愁",
                "quest_type":           "杀",
                "time":                 620,
                "exp_bonus":            220,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "余婆婆",
                "quest_type":           "杀",
                "time":                 620,
                "exp_bonus":            220,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "买卖提",
                "quest_type":           "杀",
                "time":                 620,
                "exp_bonus":            220,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "出尘子",
                "quest_type":           "杀",
                "time":                 620,
                "exp_bonus":            220,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "梅剑",
                "quest_type":           "杀",
                "time":                 620,
                "exp_bonus":            220,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "乌鸦",
                "quest_type":           "杀",
                "time":                 100,
                "exp_bonus":            20,
                "pot_bonus":            5,
                "score" :               5
        ]),
        ([      "quest":                "欧阳克",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            220,
                "pot_bonus":            35,
                "score" :               20
        ]),
        ([      "quest":                "林震南",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            160,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "羊鞭",
                "quest_type":           "寻",
                "time":                 800,
                "exp_bonus":            80,
                "pot_bonus":            25,
                "score" :               5
        ]),
        ([      "quest":                "清闻比丘",
                "quest_type":           "杀",
                "time":                 700,
                "exp_bonus":            120,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "朱丹臣",
                "quest_type":           "杀",
                "time":                 700,
                "exp_bonus":            190,
                "pot_bonus":            29,
                "score" :               5
        ]),
        ([      "quest":                "左全",
                "quest_type":           "杀",
                "time":                 700,
                "exp_bonus":            180,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "衙役服",
                "quest_type":           "寻",
                "time":                 200,
                "exp_bonus":            100,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "烧红的铁锤",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            200,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "流氓头",
                "quest_type":           "杀",
                "time":                 200,
                "exp_bonus":            30,
                "pot_bonus":            5,
                "score" :               5
        ]),
        ([      "quest":                "羊肉串",
                "quest_type":           "寻",
                "time":                 800,
                "exp_bonus":            20,
                "pot_bonus":            9,
                "score" :               5
        ]),
        ([      "quest":                "游客",
                "quest_type":           "杀",
                "time":                 100,
                "exp_bonus":            30,
                "pot_bonus":            8,
                "score" :               5
        ]),
        ([      "quest":                "摘星子",
                "quest_type":           "杀",
                "time":                 700,
                "exp_bonus":            190,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "曲灵风",
                "quest_type":           "杀",
                "time":                 700,
                "exp_bonus":            290,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "牛皮酒袋",
                "quest_type":           "寻",
                "time":                 200,
                "exp_bonus":            5,
                "pot_bonus":            3,
                "score" :               5
        ]),
        ([      "quest":                "家丁",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            50,
                "pot_bonus":            10,
                "score" :               15
        ]),
        ([      "quest":                "卖花姑娘",
                "quest_type":           "杀",
                "time":                 100,
                "exp_bonus":            30,
                "pot_bonus":            7,
                "score" :               5
        ]),
});

mapping query_quest()
{
        return quest[random(sizeof(quest))];
}

