// qlist200000.c

inherit SKILL;

mapping *quest = ({
        ([      "quest":                "黄眉大师",
                "quest_type":           "杀",
                "time":                 700,
                "exp_bonus":            200,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "段誉",
                "quest_type":           "杀",
                "time":                 700,
                "exp_bonus":            200,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "段正淳",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "刀白凤",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "高升泰",
                "quest_type":           "杀",
                "time":                 700,
                "exp_bonus":            180,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "木婉清",
                "quest_type":           "杀",
                "time":                 800,
                "exp_bonus":            240,
                "pot_bonus":            40,
                "score" :               5
        ]),
        ([      "quest":                "郭靖",
                "quest_type":           "杀",
                "time":                 800,
                "exp_bonus":            240,
                "pot_bonus":            40,
                "score" :               5
        ]),
        ([      "quest":                "灭绝师太",
                "quest_type":           "杀",
                "time":                 800,
                "exp_bonus":            240,
                "pot_bonus":            40,
                "score" :               5
        ]),
        ([      "quest":                "周芷若",
                "quest_type":           "杀",
                "time":                 800,
                "exp_bonus":            240,
                "pot_bonus":            40,
                "score" :               5
        ]),
        ([      "quest":                "虚竹",
                "quest_type":           "杀",
                "time":                 800,
                "exp_bonus":            200,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "金轮法王",
                "quest_type":           "杀",
                "time":                 800,
                "exp_bonus":            200,
                "pot_bonus":            40,
                "score" :               5
        ]),
        ([      "quest":                "嘉木活佛",
                "quest_type":           "杀",
                "time":                 800,
                "exp_bonus":            200,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "血刀老祖",
                "quest_type":           "杀",
                "time":                 800,
                "exp_bonus":            200,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "陈近南",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
         ]),
        ([      "quest":                "洪七公",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "金轮法王",
                "quest_type":           "杀",
                "time":                 800,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "鸠摩智",
                "quest_type":           "杀",
                "time":                 800,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "丁春秋",
                "quest_type":           "杀",
                "time":                 800,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "段延庆",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "达摩老祖",
                "quest_type":           "杀",
                "time":                 1800,
                "exp_bonus":            500,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "玄慈大师",
                "quest_type":           "杀",
                "time":                 800,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "玄难大师",
                "quest_type":           "杀",
                "time":                 800,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "玄悲大师",
                "quest_type":           "杀",
                "time":                 800,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "玄苦大师",
                "quest_type":           "杀",
                "time":                 800,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "玄痛大师",
                "quest_type":           "杀",
                "time":                 800,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "枯荣大师",
                "quest_type":           "杀",
                "time":                 800,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "本尘",
                "quest_type":           "杀",
                "time":                 800,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "本相",
                "quest_type":           "杀",
                "time":                 800,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "本观",
                "quest_type":           "杀",
                "time":                 800,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "本参",
                "quest_type":           "杀",
                "time":                 800,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "本参",
                "quest_type":           "杀",
                "time":                 800,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "张三丰",
                "quest_type":           "杀",
                "time":                 800,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "宋远桥",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "俞莲舟",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "俞岱岩",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "张松溪",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "张翠山",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "殷梨亭",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "莫声谷",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "黄药师",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "陈玄风",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "梅超风",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "陆乘风",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "冯默风",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "欧阳锋",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "玉玑子",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "玉音子",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "玉磬子",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "天门道人",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "岳不群",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "岳夫人",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "高老者",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "矮老者",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "莫大",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "鲁连荣",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "定静师太",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "定闲师太",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "定逸师太",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "左冷禅",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "陆柏",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "费彬",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "丁勉",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "汤英鹄",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "钟镇",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "邓八年",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "钟镇",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "高克新",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "杨逍",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "范遥",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "殷天正",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "谢逊",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "韦一笑",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "天山童姥",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "胡斐",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "向问天",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "龙岛主",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "木岛主",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "萧峰",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "洪安通",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "余沧海",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            300,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "辟邪剑谱",
                "quest_type":           "寻",
                "time":                 800,
                "exp_bonus":            80,
                "pot_bonus":            15,
                "score" :               5
        ]),
        ([      "quest":                "天香堂令牌",
                "quest_type":           "寻",
                "time":                 800,
                "exp_bonus":            80,
                "pot_bonus":            15,
                "score" :               5
        ]),
        ([      "quest":                "熊胆干",
                "quest_type":           "寻",
                "time":                 800,
                "exp_bonus":            80,
                "pot_bonus":            15,
                "score" :               5
        ]),
        ([      "quest":                "玉女剑谱",
                "quest_type":           "寻",
                "time":                 800,
                "exp_bonus":            80,
                "pot_bonus":            15,
                "score" :               5
        ]),
        ([      "quest":                "游龙剑",
                "quest_type":           "寻",
                "time":                 800,
                "exp_bonus":            80,
                "pot_bonus":            15,
                "score" :               5
        ]),
        ([      "quest":                "补天石",
                "quest_type":           "寻",
                "time":                 800,
                "exp_bonus":            80,
                "pot_bonus":            15,
                "score" :               5
        ]),
        ([      "quest":                "伏魔刀",
                "quest_type":           "寻",
                "time":                 800,
                "exp_bonus":            80,
                "pot_bonus":            15,
                "score" :               5
        ]),
        ([      "quest":                "帛卷",
                "quest_type":           "寻",
                "time":                 800,
                "exp_bonus":            80,
                "pot_bonus":            15,
                "score" :               5
        ]),
        ([      "quest":                "波斯长袍",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            250,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "木鱼槌",
                "quest_type":           "寻",
                "time":                 800,
                "exp_bonus":            250,
                "pot_bonus":            40,
                "score" :               5
        ]),
        ([      "quest":                "斗篷",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            200,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "老山人参",
                "quest_type":           "寻",
                "time":                 800,
                "exp_bonus":            270,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "蒙汗药",
                "quest_type":           "寻",
                "time":                 800,
                "exp_bonus":            270,
                "pot_bonus":            30,
                "score" :               5
        ]),

});

mapping query_quest()
{
        return quest[random(sizeof(quest))];
}


