// qslist30000.c

inherit SKILL;
#include <ansi.h>;
mapping *quest = ({
        ([      "quest":                "肥肥",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "劳德诺",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "管家",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "李教头",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "花花公子",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "小山贼",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "山贼",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "山贼头",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "仕卫", 
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "舞蛇人",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "程药发",
                "quest_type":           "杀",
                "time":                 200,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "崔员外",
                "quest_type":           "杀",
                "time":                 200,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "管家",
                "quest_type":           "杀",
                "time":                 200,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "王五",
                "quest_type":           "杀",
                "time":                 200,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "林平之",
                "quest_type":           "杀",
                "time":                 200,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "流氓",
                "quest_type":           "杀",
                "time":                 200,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "流氓头",
                "quest_type":           "杀",
                "time":                 200,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "平一指",
                "quest_type":           "杀",
                "time":                 200,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "空空儿",
                "quest_type":           "杀",
                "time":                 200,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "冼老板",
                "quest_type":           "杀",
                "time":                 200,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "小桂子",
                "quest_type":           "杀",
                "time":                 200,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "海公公",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "康亲王",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "喇嘛",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "老鸨婆",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "小流氓",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "仆役",
                "quest_type":           "杀",
                "time":                 200,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "史松",
                "quest_type":           "杀",
                "time":                 200,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "吴之荣",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "吴天德",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "小贼",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "「平通镖局」镖头",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "段无畏",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "段延庆",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "恶奴",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "管家",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "贵公子",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "何红药",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "祭司",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "老祭司",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "乌夷老祭司",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "神农帮弟子",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "无量剑弟子",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "族头人",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "族长",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "宋青书",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "忽伦大虎",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "忽伦二虎",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "焦文期",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "忽伦三虎",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "忽伦四虎",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "滕一雷",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "阎基",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "段天德",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "大金兵",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "裘千丈",
                "quest_type":           "杀",
                "time":                 200,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "完颜洪烈",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "完颜康",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "褚圆",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "刀客",
                "quest_type":           "杀",
                "time":                 100,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "管家",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "剑客",
                "quest_type":           "杀",
                "time":                 100,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "李可秀",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "龙骏",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "蒙面人",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "成德殿殿下弟子",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "日月神教教徒",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "杨莲亭",
                "quest_type":           "杀",
                "time":                 200,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "鲁连荣",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "田伯光",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "侯通海",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "梁子翁",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "马青雄",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "马贼",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "蒙面人",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "彭连虎",
                "quest_type":           "杀",
                "time":                 200,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "钱青健",
                "quest_type":           "杀",
                "time":                 200,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "沙通天",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "沈青刚",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "吴青烈",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "西夏兵",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "李铁嘴",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "九翼道人",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "乌老大",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "皇宫卫士",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "南海鳄神",
                "quest_type":           "杀",
                "time":                 600,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "努儿海",
                "quest_type":           "杀",
                "time":                 600,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "石人武士",
                "quest_type":           "杀",
                "time":                 600,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "校尉",
                "quest_type":           "杀",
                "time":                 600,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "西夏兵",
                "quest_type":           "杀",
                "time":                 600,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "一品堂武士",
                "quest_type":           "杀",
                "time":                 600,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "云中鹤",
                "quest_type":           "杀",
                "time":                 600,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "白龟寿",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "常金鹏",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "程嘲风",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "封弓影",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "高山王",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "冷谦",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "李天垣",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "彭莹玉",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "说不得",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "唐洋",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "拓跋",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "闻苍松",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "辛然",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "颜垣",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "殷无福",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "殷无禄",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "殷无寿",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "殷野王",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "张中",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "周颠",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "庄铮",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "方人智",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "洪人雄",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "侯人英",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "吉人通",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "贾人达",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "罗人杰",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "申人俊",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "于人豪",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "余人彦",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "地痞",
                "quest_type":           "杀",
                "time":                 200,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "红毛鬼",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "李莫愁",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "倭寇",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "游讯",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "行者",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "年轻女弟子",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "陆高轩",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "老者",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "无根道长",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "许雪亭",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "殷锦",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "张淡月",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "章老三",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "卜沉",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "邓八年",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "狄修",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "丁勉",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "费彬",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "高克新",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "陆柏",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "沙天江",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "史登达",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "汤英鹄",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "万大平",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "乐厚",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "钟镇",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "玉玑子",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "玉磬子",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "玉音子",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "进喜儿",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "土匪",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "土匪头",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "小土匪",
                "quest_type":           "杀",
                "time":                 200,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "巴依",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "星宿派钹手",
                "quest_type":           "杀",
                "time":                 200,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "采花子",
                "quest_type":           "杀",
                "time":                 200,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "星宿派鼓手",
                "quest_type":           "杀",
                "time":                 200,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "星宿派号手",
                "quest_type":           "杀",
                "time":                 200,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "花铁干",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "小喇嘛",
                "quest_type":           "杀",
                "time":                 200,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "守寺僧兵",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "李教头",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "欧阳克",
                "quest_type":           "杀",
                "time":                 200,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "彭有敬",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "全冠清",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "胖头陀",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "瘦头陀",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "许雪亭",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "殷锦",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "张淡月",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "阿紫",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "出尘子",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "狮吼子",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "天狼子",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "达而巴",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "葛伦布",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "贡唐仓国师",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "嘉木活佛",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "拉章活佛",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "灵智上人",
                "quest_type":           "杀",
                "time":                 600,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "萨木活佛",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "善勇",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),
        ([      "quest":                "胜谛",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            120,
                "pot_bonus":            68,
                "score" :               5
        ]),

});

mapping query_quest()
{
        return quest[random(sizeof(quest))];
}

