// qwlist5000.c

inherit SKILL;
#include <ansi.h>;
mapping *quest = ({
        ([      "quest":                "牛皮酒袋",
                "quest_type":           "寻",
                "time":                 200,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "白色长袍",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "海口大碗",
                "quest_type":           "寻",
                "time":                 300,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "草莓",
                "quest_type":           "寻",
                "time":                 300,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "柴",
                "quest_type":           "寻",
                "time":                 300,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "柴刀",
                "quest_type":           "寻",
                "time":                 300,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "大刀",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "金蛇胆",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            20,
                "pot_bonus":            16,
                "score" :               20
        ]),
        ([      "quest":                "青蛇胆",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            20,
                "pot_bonus":            16,
                "score" :               20
        ]),
        ([      "quest":                "青色丝袍",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "蛇鞭",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            20,
                "pot_bonus":            16,
                "score" :               20
        ]),
        ([      "quest":                "蛇胆膏",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            6,
                "pot_bonus":            3,
                "score" :               20
        ]),
        ([      "quest":                "蛇皮",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            6,
                "pot_bonus":            3,
                "score" :               20
        ]),
        ([      "quest":                "蛇肉",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "绣花鞋",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "兔肉",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "白色长袍",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "海口大碗",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "蛋糕",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "木柴",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "豆浆",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "蛇胆粉",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "引路神蛇",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "蛇杖",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            54,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "绣花鞋",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "草鞋",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "绣花小鞋",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "金戒指",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "狗皮",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            54,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "红烧狗肉",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "军服",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "面具",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            20,
                "pot_bonus":            16,
                "score" :               20
        ]),
        ([      "quest":                "金项链",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "牢房钥匙",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            12,
                "score" :               20
        ]),
        ([      "quest":                "衙役服",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "竹棒",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "包子",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "竹棒",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "大刀",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "拂尘",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            20,
                "pot_bonus":            16,
                "score" :               20
        ]),
        ([      "quest":                "金叶",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "黑龙鞭",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            20,
                "pot_bonus":            12,
                "score" :               20
        ]),
        ([      "quest":                "锦缎",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            26,
                "score" :               20
        ]),
        ([      "quest":                "冰糖葫芦",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "屠刀",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "腰带",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "药粉",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "绸袍",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "粗布衣",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "摆夷短裙",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "青色道袍",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "斗篷",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "对衿褂子",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "虎皮",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            20,
                "pot_bonus":            16,
                "score" :               20
        ]),
        ([      "quest":                "黄衣军服",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "砍刀",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "窄裉袄",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "贝壳项链",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "蛮刀",
                "quest_type":           "寻",
                "time":                 700,
                "exp_bonus":            20,
                "pot_bonus":            16,
                "score" :               20
        ]),
        ([      "quest":                "毛毯",
                "quest_type":           "寻",
                "time":                 700,
                "exp_bonus":            20,
                "pot_bonus":            16,
                "score" :               20
        ]),
        ([      "quest":                "白纱挑线镶边裙",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "台夷短裙",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "铁甲",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            112,
                "pot_bonus":            9,
                "score" :               20
        ]),
        ([      "quest":                "筒裙",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "台夷头巾",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "乌夷长裙",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "乌夷大麾",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            54,
                "pot_bonus":            26,
                "score" :               20
        ]),
        ([      "quest":                "白衣",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "白绸衫",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "圆领小袄",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "纺纱机",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "拂尘",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "软剑",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "皮腰带",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "淡黄衫",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "菜刀",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "青布长衫",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "袈裟",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "熊胆干",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            20,
                "pot_bonus":            16,
                "score" :               20
        ]),
        ([      "quest":                "熟铁扁担",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "杆秤",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "尖刀",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "九节鞭",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            20,
                "pot_bonus":            16,
                "score" :               20
        ]),
        ([      "quest":                "短刀",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "油纸折扇",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "粽子",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "红绸小杉",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "地牢钥匙",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "枣红缎面皮袍",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "绣花针",
                "quest_type":           "寻",
                "time":                 300,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "大珍珠",
                "quest_type":           "寻",
                "time":                 300,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "紫绸衫",
                "quest_type":           "寻",
                "time":                 300,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "紫金锤",
                "quest_type":           "寻",
                "time":                 300,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "丧门斧",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "葛布长袍",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "分水刺",
                "quest_type":           "寻",
                "time":                 600,
                "exp_bonus":            20,
                "pot_bonus":            16,
                "score" :               20
        ]),
        ([      "quest":                "三股叉",
                "quest_type":           "寻",
                "time":                 600,
                "exp_bonus":            20,
                "pot_bonus":            16,
                "score" :               20
        ]),
        ([      "quest":                "大斧头",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            20,
                "pot_bonus":            16,
                "score" :               20
        ]),
        ([      "quest":                "夜行水靠",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            20,
                "pot_bonus":            16,
                "score" :               20
        ]),
        ([      "quest":                "铁锹",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            20,
                "pot_bonus":            16,
                "score" :               20
        ]),
        ([      "quest":                "长袍",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "斗篷",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "冰雪翡翠糕",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "钥匙",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "青衣",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "酸梅汤",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "黑色长衫",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "镔铁判官笔",
                "quest_type":           "寻",
                "time":                 600,
                "exp_bonus":            20,
                "pot_bonus":            16,
                "score" :               20
        ]),
        ([      "quest":                "绣梅青衣",
                "quest_type":           "寻",
                "time":                 600,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "红绸",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "无忧红花",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "南海神木",
                "quest_type":           "寻",
                "time":                 600,
                "exp_bonus":            20,
                "pot_bonus":            16,
                "score" :               20
        ]),
        ([      "quest":                "油布包",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "白布长袍",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "铁背心",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "长鞭",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "长剑",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "禅杖",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "大还丹",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            20,
                "pot_bonus":            16,
                "score" :               20
        ]),
        ([      "quest":                "大白鱼",
                "quest_type":           "寻",
                "time":                 600,
                "exp_bonus":            20,
                "pot_bonus":            16,
                "score" :               20
        ]),
        ([      "quest":                "鱼骨",
                "quest_type":           "寻",
                "time":                 700,
                "exp_bonus":            20,
                "pot_bonus":            16,
                "score" :               20
        ]),
        ([      "quest":                "尸骨",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "阳顶天遗骨",
                "quest_type":           "寻",
                "time":                 600,
                "exp_bonus":            20,
                "pot_bonus":            16,
                "score" :               20
        ]),
        ([      "quest":                "阳夫人遗骨",
                "quest_type":           "寻",
                "time":                 600,
                "exp_bonus":            20,
                "pot_bonus":            16,
                "score" :               20
        ]),
        ([      "quest":                "皮腰带",
                "quest_type":           "寻",
                "time":                 600,
                "exp_bonus":            20,
                "pot_bonus":            16,
                "score" :               20
        ]),
        ([      "quest":                "倚天剑",
                "quest_type":           "寻",
                "time":                 800,
                "exp_bonus":            20,
                "pot_bonus":            16,
                "score" :               20
        ]),
        ([      "quest":                "阳教主遗信",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "锦缎",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "荷兰火枪",
                "quest_type":           "寻",
                "time":                 300,
                "exp_bonus":            20,
                "pot_bonus":            16,
                "score" :               20
        ]),
        ([      "quest":                "禅杖",
                "quest_type":           "寻",
                "time":                 300,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "金边黑布袈裟",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "青布僧衣",
                "quest_type":           "寻",
                "time":                 300,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "灰布镶边袈裟",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "青布镶边袈裟",
                "quest_type":           "寻",
                "time":                 300,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "金创药",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "齐眉棍",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "白布黑边袈裟",
                "quest_type":           "寻",
                "time":                 300,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "素鸡",
                "quest_type":           "寻",
                "time":                 300,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "素鸭",
                "quest_type":           "寻",
                "time":                 300,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "青布僧衣",
                "quest_type":           "寻",
                "time":                 300,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "铁手掌",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "黄布袈裟",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "护法袈裟",
                "quest_type":           "寻",
                "time":                 300,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "皮腰带",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "百花腹蛇膏",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "无名花",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "金蛇胆",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "水蜜桃",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "腹蛇胆",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "用过的百花腹蛇膏",
                "quest_type":           "寻",
                "time":                 700,
                "exp_bonus":            20,
                "pot_bonus":            16,
                "score" :               20
        ]),
        ([      "quest":                "雄黄",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "白绸裙",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "白袍",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "白丝衣",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "青布袍",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "醉仙茶",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "粗布袍",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "桃花糕",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "束发金带" ,
                "quest_type":           "寻",
                "time":                 700,
                "exp_bonus":            20,
                "pot_bonus":            16,
                "score" :               20
        ]),
        ([      "quest":                "明珠",
                "quest_type":           "寻",
                "time":                 800,
                "exp_bonus":            16,
                "pot_bonus":            12,
                "score" :               20
        ]),
        ([      "quest":                "桃木剑",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "布阵箱",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "玉萧",
                "quest_type":           "寻",
                "time":                 600,
                "exp_bonus":            20,
                "pot_bonus":            16,
                "score" :               20
        ]),
        ([      "quest":                "锦盒",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "香",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "香炉",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "游龙剑",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            12,
                "score" :               20
        ]),
        ([      "quest":                "细铁杆",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "药草",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "绝情花",
                "quest_type":           "寻",
                "time":                 800,
                "exp_bonus":            60,
                "pot_bonus":            12,
                "score" :               20
        ]),
        ([      "quest":                "石臼",
                "quest_type":           "寻",
                "time":                 800,
                "exp_bonus":            60,
                "pot_bonus":            12,
                "score" :               20
        ]),
        ([      "quest":                "阴阳合和散",
                "quest_type":           "寻",
                "time":                 800,
                "exp_bonus":            60,
                "pot_bonus":            12,
                "score" :               20
        ]),
        ([      "quest":                "女儿香",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "白色道袍",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "五行服",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "香茶",
                "quest_type":           "寻",
                "time":                 300,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "黄衫",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "柴刀",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "蜡烛",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "清茶",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "手帕",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "石块",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "椰子",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "蒙汗药",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "小蒲团",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "米饭",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "沙虫",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "沙虫壳",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "羊鞭",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "长鞭",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "波斯长袍",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "冬不拉",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "小毛驴",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "火折",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "哈密瓜",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "伊犁马",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "马奶酒壶",
                "quest_type":           "寻",
                "time":                 300,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "馕",
                "quest_type":           "寻",
                "time":                 300,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "铜钹",
                "quest_type":           "寻",
                "time":                 300,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "铜鼓",
                "quest_type":           "寻",
                "time":                 300,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "铜号",
                "quest_type":           "寻",
                "time":                 300,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "阿拉伯弯刀",
                "quest_type":           "寻",
                "time":                 300,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "维吾尔族长袍",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "天山雪莲",
                "quest_type":           "寻",
                "time":                 300,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "花雕酒袋",
                "quest_type":           "寻",
                "time":                 300,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "药锄",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "清心散",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "鸟羽大氅",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "法轮",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "木棍",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "牛皮袋",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "青稞面",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "翠绿绸衫",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "金项链",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "粉红绸衫",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "碧螺春",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
});

mapping query_quest()
{
        return quest[random(sizeof(quest))];
}
